version: "3.6"

networks:
  appnet:

services:
  api:
    image: revaturecloud/servicehub-user:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
        reservations:
          cpus: "0.25"
          memory: "128M"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    environment:
      ConnectionStrings__MongoDB: mongodb://root:password123@db
    networks:
      - appnet
    ports:
      - "9000:80"
  db:
    image: mongo:3.6
    deploy:
      replicas: 1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    networks:
      - appnet

volumes:
  appdata:
